#ifndef _ICON_H_
#define _ICON_H_

static const char* move_xpm[]={
    "124 30 4 1",
    "b c #000000",
    ". c none",
    "d c none",
    "a c #ffffff",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.............aa.............",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............abba............",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...........abbbba...........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..........abbbbbba..........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........abbbbbbbba.........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd........aaaaabbaaaaa........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......aa....bb....aa.......",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......aba....bb....aba......",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.....abba....bb....abba.....",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd....abbbaaaaabbaaaaabbba....",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...abbbbbbbbbbbbbbbbbbbba...",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...abbbbbbbbbbbbbbbbbbbba...",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd....abbbaaaaabbaaaaabbba....",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.....abba...abba...abba.....",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd......aba...abba...aba......",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.......aa...abba...aa.......",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd........aaaaabbaaaaa........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.........abbbbbbbba.........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd..........abbbbbba..........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd...........abbbba...........",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............abba............",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd.............aa.............",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd............................",
    };

static const char* cap_xpm[]={
    "24 24 3 1",
    "b c #000000",
    ". c none",
    "a c #ffffff",
    "........................",
    "........................",
    "....a..............a....",
    "....aba..........aba....",
    ".....aba........aba.....",
    "......aba......aba......",
    ".......aba....aba.......",
    "........aba..aba........",
    ".........abaaba.........",
    "..........abbaa.........",
    ".........abaaba.........",
    "........abbaabba........",
    ".......abba..abba.......",
    ".....aabba....abba......",
    "....abbbba....abbbba....",
    "...abbbbbba..abbbbbba...",
    "..abbaaaabbaabbaaaabba..",
    "..abba..abbaabba..abba..",
    "..abbaaaabbaabbaaaabba..",
    "...abbbbbba..abbbbbba...",
    "....abbbba..abbbbbba....",
    ".....aaaa..abaaaaaa......",
    "............a...........",
    "........................",
    };

static const char* exit_xpm[]={
    "24 24 3 1",
    "b c #000000",
    ". c none",
    "a c #ffffff",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    "....................aaa.",
    "...................abba.",
    "..................abbba.",
    ".....aaa.........abbba..",
    "....abba........abbba...",
    "...abba........abbba....",
    "..abbaaaaaaaaaabbba.....",
    ".abbbbbbbbbbbbbbba......",
    ".abbbbbbbbbbbbbba.......",
    "..abbaaaaaaaaaaa........",
    "...abba.................",
    "....abba................",
    ".....aaa................",
    "........................",
    "........................",
    "........................",
    "........................",
    "........................",
    };

static const char* alert_none_xpm[]={
    "24 24 4 1",
    "b c #000000",
    ". c none",
    "a c #ffffff",
    "c c #ff0000",
    "........................",
    "........................",
    "...........aa...........",
    "..........abba..........",
    ".........abbbba.........",
    ".......abbbaabbba.......",
    "......abbbaaaabbba......",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaaccc.....",
    ".....abbaaaaaaacaaac....",
    "....abbbbbbbbbcaaaaac...",
    "...abbbbbbbbbcaaaaacac..",
    "...aaaaabbaaacaaaacaac..",
    "........abbbbcaaacaaac..",
    ".........abbbbcacaaac...",
    "..........aaaa.caaac....",
    "................ccc.....",
    "........................",
    };
static const char* alert_sound_xpm[]={
    "24 24 3 1",
    "b c #000000",
    ". c none",
    "a c #ffffff",
    "........................",
    "........................",
    "...........aa...........",
    "..........abba..........",
    ".........abbbba.........",
    ".......abbbaabbba.......",
    "......abbbaaaabbba......",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    ".....abbaaaaaaaabba.....",
    "....abbbbbbbbbbbbbba....",
    "...abbbbbbbbbbbbbbbba...",
    "...aaaaabbaaaabbaaaa....",
    ".....bbbabbbbbbabbb.....",
    "...bb.b.babbbbab.b.bb...",
    ".bb..b..b.aaaa.b..b..bb.",
    "....b...b......b...b....",
    "........................",
    };

static const char* alert_fblight_xpm[]={
    "24 24 4 1",
    "b c #000000",
    ". c none",
    "a c #ffffff",
    "c c #ffff00",
    "........................",
    "........................",
    ".........aaaaaa.........",
    "........abbbbbba........",
    ".......abbbbbbbba.......",
    "......abbaaaaaabba......",
    ".....abbaaaaaaaabba.....",
    "....abbaaaaaaaaaabba....",
    "....abbaaaaaaaaaabba....",
    "....abbaaaaaaaaaabba....",
    "....abbaaaaaaaaaabba....",
    "....abbaaaaaaaaaabba....",
    "....abbaababaabaabba....",
    ".....abbababaababba.....",
    "......abbabaababba......",
    ".......abbabbabba.......",
    "........abbbbbba........",
    "........abb..bba........",
    "........abb..bba........",
    ".........ab..ba.........",
    "..........abba..........",
    "...........aa...........",
    "........................",
    "........................",
    };

static const char* alert_vibrate_xpm[]={
    "24 24 4 1",
    "b c #000000",
    ". c none",
    "a c #ffffff",
    "c c #ff0000",
    "........................",
    "........................",
    "...........aa...........",
    "..........abba..........",
    ".........abbbba.........",
    ".......abbbaabbba.......",
    "......abbbaaaabbba......",
    ".....abbaaaccaaabba.....",
    ".....abbaaccaaaabba.....",
    ".....abbaaaccaaabba.....",
    ".....abbaaccaaaabba.....",
    ".....abbaaaccaaabba.....",
    ".....abbaaccaaaabba.....",
    ".....abbaaaccaaabba.....",
    ".....abbaaccaaaabba.....",
    ".....abbaaaaaaaabba.....",
    "....abbbbbbbbbbbbbba....",
    "...abbbbbbbbbbbbbbbba...",
    "...aaaaabbaaaabbaaaa....",
    "........abbbbbba........",
    ".........abbbba.........",
    "..........aaaa..........",
    "........................",
    "........................",
    };
#endif
